language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage coveralls mock requests
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then pip install git+https://github.com/thumbor/libthumbor@master; else pip install -q libthumbor; fi
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls
