language: python

matrix:
  include:
  - python: 2.7
    env: DJANGO_VERSION=1.11.22
  - python: 3.6
    env: DJANGO_VERSION=1.11.22
  - python: 3.6
    env: DJANGO_VERSION=2.0.13
  - python: 3.6
    env: DJANGO_VERSION=2.1.10
  - python: 3.6
    env: DJANGO_VERSION=2.2.3

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage coveralls libthumbor mock requests
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls
