language: python

python:
  - 2.7
  - 3.4

env:
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.4
  - DJANGO_VERSION=1.8.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage coveralls mock requests
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls
