language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.11.17

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install coverage coveralls libthumbor mock requests
  - pip install .

before_script: cd tests

script: make coverage

after_script: coveralls
